### PR TITLE
⏳ Session ending dialog

### PR DESCRIPTION
**Pull request by donalnofrixion**
This PR adds a Session Ending Notification Dialog. ⏳

The dialog appears after 4 minutes (regular user) or 29 minutes (PaymentRequester) of inactivity with a 60 second countdown prompting the user to stay logged in. A sound is also played when the dialog opens.

The session timeout is synched across browser tabs and will either keep the user logged in on all tabs or log out all tabs.

**Keep me logged in**

https://github.com/nofrixion/nofrixion.business/assets/89344328/ff4187f1-fa56-40e7-9a83-28a1ae4316fd

**Session end**

https://github.com/nofrixion/nofrixion.business/assets/89344328/952a3523-0188-4c90-97c6-356b17d1f795

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/140.

**Review by sipsorcery — APPROVED** [review]

**Review by sauravmaiti22 — APPROVED** [review]

**Review by Publicker — APPROVED** [review]
🔥🔥🔥 It worked flawlessly for me.

Just a quick note –  I know you mentioned in the daily meeting that the notification sounds wouldn't work without certain permissions and as you said, there was no sound when the session ending modal popped up for me. However, I noticed there's an audio integration in the code, which was also mentioned in the PR description. Does this mean the notification sound only works in specific browsers, and the code is included for those cases?

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/140.

**Comment by donalnofrixion** [comment]
> 🔥🔥🔥 It worked flawlessly for me.
> 
> 
> 
> Just a quick note –  I know you mentioned in the daily meeting that the notification sounds wouldn't work without certain permissions and as you said, there was no sound when the session ending modal popped up for me. However, I noticed there's an audio integration in the code, which was also mentioned in the PR description. Does this mean the notification sound only works in specific browsers, and the code is included for those cases?

A sound can only be played after a user has interacted with the document according to chrome's dev channel. If it still doesn't play it might be the build. I'll check that

**Comment by pabloi-nf** [comment]
@donalnofrixion @Publicker the sound worked perfectly for me

**Comment by donalnofrixion** [comment]
> > @donalnofrixion @Publicker the sound worked perfectly for me
> 
> Which browser are you using @pabloi-nf?

The sound works in Chrome after interacting with the document.
It doesn't work in Safari. I think it might be a browser setting.

image

**Comment by pabloi-nf** [comment]
@Publicker Chrome
image

**Review by arifmatin — APPROVED** [review]

**Comment by Publicker** [comment]
Got it, thanks guys, @donalnofrixion @pabloi-nf.

I tested it on both Chrome and Safari just now. As @donalnofrixion mentioned, it didn't work, but unexpectedly, it also failed on Chrome.

image

The error reads: `Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD`. This aligns with what the Chrome Dev Channel suggests. However, it's odd to see this message since interacting with the site is necessary to even view the modal.

It seems I'm the only one not hearing the sound, so no need to worry too much.

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
Everything worked well, but I noticed something odd about the sound.
I was in another tab and I could see by the title that the countdown already started, even when I didn't hear the sound. When I went back to the tab the sound played, when the countdown was already in 35s.

Another thing that we can add is the possibility that clicking outside the box or pressing ESC cancels the countdown. Does that makes sense? I think it's good to allow both options to stay signed in: confirming with the button or canceling the countdown

**Comment by pabloi-nf** [comment]
@donalnofrixion now the sound is working as expected after that first time. It plays even when I'm in another app

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/140.

**Comment by donalnofrixion** [comment]
Hi @pabloi-nf I've added click outside and esc as a way of cancelling the session timeout. I can't repro the sound issue.

**Review by pabloi-nf — APPROVED** [review]
The sound is not essential, it should be only a helper. It worked fine now. I think we can move forward with it.

**Pull request merged**
