### PR TITLE
Fix Account Card Arrows (in carousel)

### PR DESCRIPTION
**Pull request by Publicker**
In this pull request:

1. Fixed an issue where the arrows used to scroll through the current account cards weren't visible on initial load. With this fix, arrows will always be displayed if there's a card to be shown, whether on the left or right side of the screen.
2. Updated the card designs to align more closely with the specified design. This includes adding a gradient to the edges near the arrows.

**Important Note**: Due to some limitations, introducing the gradient arrows required a trade-off. The snapping feature on the cards has been removed. Now, clicking on the arrow will scroll a fixed amount of content instead of snapping the card to the beginning. If we kept the snapping feature, cards would align directly to the screen's edge without any padding.

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/38.

**Review by sipsorcery — APPROVED** [review]

**Comment by sipsorcery** [comment]
Just my 2c. Having the arrows disappear is a,little bit disconcerting. WHen using I feel more comfortable if they get disabled. Could just be me though.

**Review by sauravmaiti22 — APPROVED** [review]

**Review by arifmatin — APPROVED** [review]

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
The behaviour looks good.
There is an issue with the shadow when the mouse is over the card. As you can see, it looks cropped on the top and bottom edge.
image

**Comment by pabloi-nf** [comment]
> Just my 2c. Having the arrows disappear is a,little bit disconcerting. WHen using I feel more comfortable if they get disabled. Could just be me though.

@sipsorcery \ The principle here is to show the arrow only when it's needed, as a way to indicate more clearly when there are more elements hiding and when there aren't. It's not uncommon to see this pattern. Here is an example from another website.

https://github.com/nofrixion/nofrixion.business/assets/127946572/4ae4970a-b0ae-4664-a793-0dbda377b200

**Comment by sipsorcery** [comment]
@pabloi-nf in that video the arrows get disabled rather than disappearing. I guess it's a tradeoff between removing UI elements that aren't need to reduce clutter and causing confusion in the user when they are trying to find something they think should be there. Once the arrows disappear my instinct is to look around and find where they have gone to. If they get disabled I immediately comprehend what it means.

**Comment by pabloi-nf** [comment]
@sipsorcery In the video they disappear when there are no more elements to show. It can be seen on the arrow on the left. At first is not displayed, then it's displayed when the list moves to the left, and then disappears again when we move back to the beginning of the list.

If we keep showing the arrow it can be confused that there are more elements to show to that side, when they aren't. Removing the arrows make is more clear that you reached the end of the list.

This is another example from Google search results, where you can see how it disappears from both sides when there are no more elements to show.

https://github.com/nofrixion/nofrixion.business/assets/127946572/3c662c74-d0c8-4c81-854d-0ced84f9ab2b

**Comment by sipsorcery** [comment]
Ok, fair enough. Loos like it's a common approach and probably only bothers me because of my old, slow brain :(.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/38.

**Review by pabloi-nf — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/38.

**Pull request merged**
