### PR TITLE
Add Account Graphic (Chart) UI

### PR DESCRIPTION
**Pull request by Publicker**
This pull request introduces a new component - the Account Graphic (Chart)UI.

You can test this component in Storybook under "[Molecules/Account Chart](https://64d9fa344203198b9ba80047-rwzqtffbab.chromatic.com/?path=/story/molecules-account-chart--default)" Additionally, you have the flexibility to manipulate the chart's data by adjusting the `points` and `currency` props.

Demo video showing how to do so:

https://github.com/nofrixion/nofrixion.business/assets/52673485/48912fc1-7b51-4b55-9c36-afe1ef9e86a2

### CODE REVIEW

**Comment by donalnofrixion** [comment]
🔥

**Review by sauravmaiti22 — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/115.

**Review by arifmatin — APPROVED** [review]

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
Looks good!

Remember that the background has a different opacity on hover.
image

By default the opacity should be 20%, and change to 30% on hover.
The colour is #40BFBF.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/115.

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
