### PR TITLE
Approve payout

### PR DESCRIPTION
**Pull request by sauravmaiti22**
Create and approve payout

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/59.

**Review by donalnofrixion — APPROVED** [review]

**Comment by Publicker** [comment]
Hey @sauravmaiti22, everything looks good, but I have a small observation. It'd also be great to get @pabloi-nf's thoughts on this. I've noticed that after initiating the payout in the "Create & Approve" flow, there's about a 2-second delay for me (though it probably varies with network speed) before the modal closes and transitions to the Approval screen. Would it be possible to adjust this so the button remains in a loading state until the user gets redirected? The current sequence felt a bit disorienting: the modal closed, I got an alert, and then I was redirected. I think it'd be smoother if the button just remained in its loading state, and then directly took me to the Approval screen without the modal closing or any tooltip popping up.

Video:

https://github.com/nofrixion/nofrixion.business/assets/52673485/dbfae85e-4c00-451e-850f-893312b5bc72

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
Agree with what @Publicker says. If the user wants to create and approve, we shouldn't show a "Payout created" notification, we should immediately send them to the approval screen. That means that we don't change state until that happens, only the loading button.

Another thing I noticed is that if I save the payout for later approval and then press on "create payout" again, it loads all the info from the last payout. In this case the fields should be empty.

Is the "edit payout" available yet? Because it doesn't open anything when I press the button.

Also, is the approval screen included in this PR? The current one is not updated with the design 
image

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/59.

**Comment by sauravmaiti22** [comment]
> Hey @sauravmaiti22, everything looks good, but I have a small observation. It'd also be great to get @pabloi-nf's thoughts on this. I've noticed that after initiating the payout in the "Create & Approve" flow, there's about a 2-second delay for me (though it probably varies with network speed) before the modal closes and transitions to the Approval screen. Would it be possible to adjust this so the button remains in a loading state until the user gets redirected? The current sequence felt a bit disorienting: the modal closed, I got an alert, and then I was redirected. I think it'd be smoother if the button just remained in its loading state, and then directly took me to the Approval screen without the modal closing or any tooltip popping up.
> 
> Video:
> 
>  2s.after.creating.Payout.mp4

Thanks @Publicker for pointing this out. I implemented it quickly yesterday, looked a bit weird to me as well. Should be okay now. I have put a 3 second timeout to the redirect.

**Comment by sauravmaiti22** [comment]
> Agree with what @Publicker says. If the user wants to create and approve, we shouldn't show a "Payout created" notification, we should immediately send them to the approval screen. That means that we don't change state until that happens, only the loading button.
> 
> Another thing I noticed is that if I save the payout for later approval and then press on "create payout" again, it loads all the info from the last payout. In this case the fields should be empty.
> 
> Is the "edit payout" available yet? Because it doesn't open anything when I press the button.
> 
> Also, is the approval screen included in this PR? The current one is not updated with the design image

@pabloi-nf The first two issues should be fixed now. Edit payout is not implemented yet. And the approval screen has to be updated in the identity server which is a separate task.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/59.

**Comment by Publicker** [comment]
> Thanks @Publicker for pointing this out. I implemented it quickly yesterday, looked a bit weird to me as well. Should be okay now. I have put a 3 second timeout to the redirect.

Thanks for checking that out @sauravmaiti22. But I'm not convinced that a timeout is the ideal solution here. The problem is, timeouts are fixed, and Payout creation times can vary a lot. I tested this using the Devtool set to "Slow 3G" mode. Interestingly, even when the Payout got approved, there was still an error tooltip, and the user was redirected. Maybe we should consider an async/await callback after the Payout's creation. This could help decide whether to redirect or display an error tooltip.

I've attached a video of my "Slow 3G" test for reference:

https://github.com/nofrixion/nofrixion.business/assets/52673485/2d1b4809-f19b-42bd-88ed-86da4504048b

**Comment by sauravmaiti22** [comment]
> > Thanks @Publicker for pointing this out. I implemented it quickly yesterday, looked a bit weird to me as well. Should be okay now. I have put a 3 second timeout to the redirect.
> 
> Thanks for checking that out @sauravmaiti22. But I'm not convinced that a timeout is the ideal solution here. The problem is, timeouts are fixed, and Payout creation times can vary a lot. I tested this using the Devtool set to "Slow 3G" mode. Interestingly, even when the Payout got approved, there was still an error tooltip, and the user was redirected. Maybe we should consider an async/await callback after the Payout's creation. This could help decide whether to redirect or display an error tooltip.
> 
> I've attached a video of my "Slow 3G" test for reference:
> 
>  Timeout.with.Slow.3G.mp4

@Publicker The payout creation is already awaited so that is not the problem here. The problem is that the state payoutID is taking some time to set and take effect to submit the approval form. 

> > Thanks @Publicker for pointing this out. I implemented it quickly yesterday, looked a bit weird to me as well. Should be okay now. I have put a 3 second timeout to the redirect.
> 
> Thanks for checking that out @sauravmaiti22. But I'm not convinced that a timeout is the ideal solution here. The problem is, timeouts are fixed, and Payout creation times can vary a lot. I tested this using the Devtool set to "Slow 3G" mode. Interestingly, even when the Payout got approved, there was still an error tooltip, and the user was redirected. Maybe we should consider an async/await callback after the Payout's creation. This could help decide whether to redirect or display an error tooltip.
> 
> I've attached a video of my "Slow 3G" test for reference:
> 
>  Timeout.with.Slow.3G.mp4

@Publicker The create payout call is already awaited and not the problem here. The approve form submit is taking some time to redirect so I think timeout is fine. I'll increase the timeout to 6 seconds. We can keep it at the highest so you don't see any issue at the lowest possible speed.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/59.

**Review by pabloi-nf — APPROVED** [review]

**Review by arifmatin — APPROVED** [review]

**Pull request merged**
