### PR TITLE
Fixed issue with updating tags

### PR DESCRIPTION
**Pull request by sauravmaiti22**
- The root cause of the issue was that we were not updating the local payment request but the list of payment requests after creating a tag.
- Even after making that change, there was a lag when modal is closed and opened again because the new tag was not in react query cache.
- Hence, created hooks for tag management to use mutation and invalidate 2 queries - single payment request and the list. It's working smoothly now.
- One issue I can think of now is that, if 2 users are simultaneously on the same payment request modal and they add tags, there are chances of loss of tags. It maybe a rare scenario now. But a future solution would be to invalidate the single payment request before making any changes to PR tags which will get the latest tags at that moment, get it from cache and then update the PR. This will result in more API calls but will avoid any loss of tags. We can think about implementing it later.

### CODE REVIEW

**Comment by donalnofrixion** [comment]
Looks good Saurav! 

One thing I noticed is if you create a brand new tag it doesn't become available in the dropdown unless the whole page is refreshed.

**Comment by sauravmaiti22** [comment]
> Looks good Saurav!
> 
> One thing I noticed is if you create a brand new tag it doesn't become available in the dropdown unless the whole page is refreshed.

Oh okay. Let me check. Thanks Donal!

**Review by donalnofrixion — APPROVED** [review]

**Comment by sauravmaiti22** [comment]
> Looks good Saurav!
> 
> One thing I noticed is if you create a brand new tag it doesn't become available in the dropdown unless the whole page is refreshed.

@donalnofrixion This should be fixed now. Had to invalidate the merchant tags query as well.

**Comment by donalnofrixion** [comment]
> > Looks good Saurav!
> > One thing I noticed is if you create a brand new tag it doesn't become available in the dropdown unless the whole page is refreshed.
> 
> @donalnofrixion This should be fixed now. Had to invalidate the merchant tags query as well.

 Great!

**Pull request merged**
