### PR TITLE
Feature/moov 2356 Connected account failure fix

### PR DESCRIPTION
**Pull request by arifmatin**
OpenBanking authorisation error received as query parameter and displayed in a toast.

https://github.com/nofrixion/nofrixion.business/assets/92720032/55312a34-f43d-4546-8e74-389a28a5f87d

### CODE REVIEW

**Review by donalnofrixion — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/118.

**Comment by Publicker** [comment]
Functionality looks great, but could we make the error messages more user-friendly? It might be helpful to have a list of possible errors so that we can make them as informative as possible. Maybe @pabloi-nf could help with that.

**Comment by arifmatin** [comment]
@Publicker The error message is coming from the API. When the user cancels an authorisation, the bank redirects to the API without a consent token. This throws a consent token not found error. We can defiantly change the wording there.

**Comment by pabloi-nf** [comment]
@arifmatin is this the case Andrés discovered last time? When an IBAN was already connected by another merchant? Or are we covering more scenarios?

As a general rule, we should NEVER put errors on toast messages. The risk is that they dissappear quickly, and the user may not understand what the problem is, or remember what was the message saying when they need to report the problem.

We made this generic error for things like this. I need to adapt the message and the icon for this specific error.
image

**Comment by arifmatin** [comment]
@pabloi-nf This is for displaying api related errors around the connected accounts in mm4b. Before errors were not getting passed to mm4b. With this change the error is in mm4b and we can display in a toast or popup modal. Currently errors are in a toast so that's what I used.

**Pull request merged**
