### PR TITLE
Feature/moov 2209 batch approvals

### PR DESCRIPTION
**Pull request by donalnofrixion**
Added support for batch approvals

### CODE REVIEW

**Comment by donalnofrixion** [comment]
https://github.com/nofrixion/nofrixion.business/assets/89344328/47916ba8-057a-4ac6-8980-4d60366c71ab

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/61.

**Comment by sipsorcery** [comment]
UI works great!

Should the batch payout submits be working or is that still todo?

image

**Comment by donalnofrixion** [comment]
> UI works great!
> 
> Should the batch payout submits be working or is that still todo?
> 
> image

Yep. They should be working. Just tried it there and it worked fine

**Comment by donalnofrixion** [comment]
@sipsorcery Those errors are happening in the worker

**Comment by sipsorcery** [comment]
Turns out submit problem wasn't related to this PR, cause was MOOV-2268 putting 'undefined' into the payout sortcode. Fixing that allowed the batch submit to work.

One suggested improvement, if it's not a big job, would be to make the checkbox column on the pending approvals page not active to open the payotu details page. I seem to manage to miss the checkbox everytime on the first attempt and end up with the details panel opening. I then slow down and make the action more deliberate but still occassionally miss.

**Comment by donalnofrixion** [comment]
> Turns out submit problem wasn't related to this PR, cause was MOOV-2268 putting 'undefined' into the payout sortcode. Fixing that allowed the batch submit to work.
> 
> 
> 
> One suggested improvement, if it's not a big job, would be to make the checkbox column on the pending approvals page not active to open the payotu details page. I seem to manage to miss the checkbox everytime on the first attempt and end up with the details panel opening. I then slow down and make the action more deliberate but still occassionally miss.

Yeah sounds good. I'll fix that first thing

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/61.

**Review by sipsorcery — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/61.

**Review by arifmatin — APPROVED** [review]

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
We should use the hover state to mark the selected rows, to make more clear which ones you are including on the list.

It's great the animation on the button, but one thing I noticed is that it makes an unnecessary side movement when changes state. It should stay always in the same position. Video attached. 

https://github.com/nofrixion/nofrixion.business/assets/127946572/dcf063ce-084d-4c21-9539-1dadd73a770d

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/61.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/61.

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
