### PR TITLE
Respect the logged in User's role and restrict functionality and routing the user does not have access to

### PR DESCRIPTION
**Pull request by donalnofrixion**
This PR implements user role logic in mm4b

1. Hide or display menu options depending on user's role
2. If user is not an 'Approver' remove all payout 'Authorise' functionality
3. Block routing to a page a user does not have access to it
4. Allow user management only for 'AdminApprover'
5. If user is PaymentRequester navigate to accounts receivable after log in

TODO:

1. Implement newly registered page
2. Implement not authorised page

### CODE REVIEW

**Review by sauravmaiti22 — APPROVED** [review]
Works great!

**Review by arifmatin — APPROVED** [review]

**Comment by Publicker** [comment]
Absolutely love this PR! It runs incredibly smoothly and the solution is so sleek! 🔥🔥🔥

**Comment by Publicker** [comment]
Just one comment - my network's been slow since a big storm from last night; it looks like it might have damaged some cables 😕.  Thanks to that, when trying to login in, I noticed the 'Not authorized' message pops up briefly before the actual page loads. It's not a major issue at the moment since it's just text, but I'm concerned it could be jarring for users once our full design is in place. Instead of momentarily seeing that state/page, could we have them see the standard NoFrixion loading animation? I think it'd make for a smoother experience.

I've captured this in a video for you to see exactly what I'm talking about: 

https://github.com/nofrixion/nofrixion.business/assets/52673485/7acec26a-edf2-4f19-93bb-ed0d25cb4b9b

**Comment by donalnofrixion** [comment]
> Absolutely love this PR! It runs incredibly smoothly and the solution is so sleek! 🔥🔥🔥

❤️

**Comment by donalnofrixion** [comment]
> Just one comment - my network's been slow since a big storm from last night; it looks like it might have damaged some cables 😕. Thanks to that, when trying to login in, I noticed the 'Not authorized' message pops up briefly before the actual page loads. It's not a major issue at the moment since it's just text, but I'm concerned it could be jarring for users once our full design is in place. Instead of momentarily seeing that state/page, could we have them see the standard NoFrixion loading animation? I think it'd make for a smoother experience.
> 
> I've captured this in a video for you to see exactly what I'm talking about:
> 
>  Not.authorised.visible.for.1.sec.mp4

Thanks for testing @Publicker 
I've added a Loader to the 'RoleProtectedRoute' component

**Review by Publicker — APPROVED** [review]

**Pull request merged**
