### PR TITLE
Decrease Latest Transaction Skeleton Height

### PR DESCRIPTION
**Pull request by Publicker**
Decreased the height of the latest transaction skeleton from 16px to 14px.

Note: The easiest way to observe the skeleton is by visiting Storybook under "Molecules/Cards/LatestTransactionsCard/With Loading."

Demo video showcasing the transition from the loaded state to the loading state in Storybook:

https://github.com/nofrixion/nofrixion.business/assets/52673485/0ebc044f-9b74-4bd9-847c-ba78d07c83f2

### CODE REVIEW

**Review by donalnofrixion — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/120.

**Review by sipsorcery — APPROVED** [review]

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
They still look tall and too dark.
Let's reuse the same styles as for the PR list and accounts module.
They also need to match roughly the position and length of the data that is loading there.
image

I made a component variant to show how it should look
https://www.figma.com/file/Sc96Upmn3MpOmvM9jgvaUG/MMB-Portal-%2F-HiFi?type=design&node-id=5224%3A33863&mode=design&t=frFn9NjilpUnsbNZ-1

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/120.

**Comment by Publicker** [comment]
@pabloi-nf Thanks for that! Should be better now! ([link](https://64d9fa344203198b9ba80047-wcpdlubjdz.chromatic.com/?path=/story/molecules-cards-latesttransactionscard--with-loading))

**Review by arifmatin — APPROVED** [review]

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
