### PR TITLE
Replace `trimEnd` with `trim` for build compatibility

### PR DESCRIPTION
**Pull request by Publicker**
This PR addresses a build issue in the web-components library where the 'trimEnd' function was causing a build error. To resolve this, we have replaced `trimEnd` with `trim`, which ensures build compatibility.

While this change affects the user experience slightly by removing leading spaces when a user moves away from an input field, it is a necessary adjustment for build stability. Two videos demonstrating the before and after behaviours have been attached for reference.

# Before

https://github.com/nofrixion/nofrixion.business/assets/52673485/988f23af-2833-44d5-a5e5-4a7996380047

# After

https://github.com/nofrixion/nofrixion.business/assets/52673485/c89ea59b-5ff1-44e5-aa3d-5b99c9190294

### CODE REVIEW

**Review by donalnofrixion — APPROVED** [review]

**Comment by donalnofrixion** [comment]
@Publicker What do think about adding a build to the pre-commit hook?

**Review by sipsorcery — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/139.

**Comment by sipsorcery** [comment]
> @Publicker What do think about adding a build to the pre-commit hook?

I was going to suggest the same. If there are linting steps to block commtis on whitepace then a failed build should definitely block it.

**Comment by Publicker** [comment]
> @Publicker What do think about adding a build to the pre-commit hook?

Yeah, I've been considering adding a feature to check the web-components build in some way too. I'm a bit hesitant about using a pre-commit hook though. I timed the build, and it takes around 20 seconds. It's not the end of the world, but waiting those 20 seconds for every commit feels a bit off. Another approach might be to run the build through the CI process. If it fails, it could trigger a failure check on the PR. This idea seems ideal to me, but it depends on extra work from the DevOps team. In the meantime, maybe we could implement the pre-commit hook while keeping in mind the need to refine it or discuss alternative solutions. What do you think @donalnofrixion?

**Comment by donalnofrixion** [comment]
> > @Publicker What do think about adding a build to the pre-commit hook?
> 
> Yeah, I've been considering adding a feature to check the web-components build in some way too. I'm a bit hesitant about using a pre-commit hook though. I timed the build, and it takes around 20 seconds. It's not the end of the world, but waiting those 20 seconds for every commit feels a bit off. Another approach might be to run the build through the CI process. If it fails, it could trigger a failure check on the PR. This idea seems ideal to me, but it depends on extra work from the DevOps team. In the meantime, maybe we could implement the pre-commit hook while keeping in mind the need to refine it or discuss alternative solutions. What do you think @donalnofrixion?

Yeah. A CI build would be the best approach. I reckon add it to the pre-commit for now and see how annoying it is 😤 Turborepo caches the builds so hopefully it won't be too annoying.

**Comment by donalnofrixion** [comment]
@Publicker We could add it to a pre-push hook instead

**Comment by Publicker** [comment]
> Yeah. A CI build would be the best approach. I reckon add it to the pre-commit for now and see how annoying it is 😤 Turborepo caches the builds so hopefully it won't be too annoying.

You're right! I forgot to take Turborepo into account for this. Great point.


> @Publicker We could add it to a pre-push hook instead

Yeah, that sounds better! Thanks for looking into this @donalnofrixion. I'll add the pre-push hook and make it run the build command.

**Review by donalnofrixion — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/139.

**Review by pabloi-nf — APPROVED** [review]

**Review by sauravmaiti22 — APPROVED** [review]

**Pull request merged**
