### PR TITLE
Integrate Account Chart into Dashboard

### PR DESCRIPTION
**Pull request by Publicker**
Description:
- Integrated the Account Chart into the Dashboard. (Credits to Saurav for handling most of the integration work!!!!)
- Addressed `flex` and responsive design challenges.
- Added mobile-responsive behaviour for improved mobile viewing.

| Desktop | Mobile |
|--------|--------|
|  Desktop | Mobile |

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/124.

**Review by donalnofrixion — APPROVED** [review]

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
Avoid the graph to be a link to the accounts page

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/124.

**Comment by Publicker** [comment]
@pabloi-nf It should not navigate to Current Accounts when tapping on the chart now!

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
