### PR TITLE
New component for FOR column in payment request table.

### PR DESCRIPTION
**Pull request by sauravmaiti22**
Found an issue with Contact component which is primarily for the payment request details modal which displays the name and email of customer. This component was reused for the FOR column but it's actually different from contact. Created a separate component which covers all cases when some or the other data won't be available.

Check the storybook to go through all the cases.

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/190.

**Review by Publicker — APPROVED** [review]

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
Thanks Saurav.

Looking at the table I noticed it can become confusing if the data changes style depending of what data is present.

For example, in the following image, it's difficult to understand that "Hamilton Smith Ltd" is the customer when it's displayed the same as "Xero Invoice INV-0027", which it's the product title.

image
<br/><br/>
  
I think we should not change the style of the 2 fields. Can we do something like this states instead?
  
image

**Comment by sauravmaiti22** [comment]
> Thanks Saurav.
> 
> Looking at the table I noticed it can become confusing if the data changes style depending of what data is present.
> 
> For example, in the following image, it's difficult to understand that "Hamilton Smith Ltd" is the customer when it's displayed the same as "Xero Invoice INV-0027", which it's the product title.
> 
> image
> 
> I think we should not change the style of the 2 fields. Can we do something like this states instead?
> 
> image

Yeah I was thinking the same. This is a good idea. Let me implement it.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/190.

**Review by Publicker — APPROVED** [review]

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
