### PR TITLE
Payout Cancel Authorisation

### PR DESCRIPTION
**Pull request by donalnofrixion**
1. Implemented "Cancel authorisation" for a payout
2. Created component "ConfirmButton"
3. Added useUpdatePayout hook

https://github.com/nofrixion/nofrixion.business/assets/89344328/36402b5b-146c-4d61-a244-49dbbbee239d

### CODE REVIEW

**Review by sipsorcery — APPROVED** [review]

**Review by Publicker — APPROVED** [review]
Loved that confirmation button!!! 🔥

**Review by arifmatin — APPROVED** [review]

**Comment by pabloi-nf** [comment]
@donalnofrixion when I cancel the authorisation of a scheduled payout that has a payment date in the future, the payout goes back to pending authorisation state, but the payment date changes to "immediately".
Isn't that a problem? If I authorise that payout again it would be paid immediately, and not in the date it was originally created to be paid of.

**Comment by donalnofrixion** [comment]
> @donalnofrixion when I cancel the authorisation of a scheduled payout that has a payment date in the future, the payout goes back to pending authorisation state, but the payment date changes to "immediately". Isn't that a problem? If I authorise that payout again it would be paid immediately, and not in the date it was originally created to be paid of.

That's by design. What you are actually cancelling is the payout's schedule. When the edit payout is implemented you will be able to add a new schedule date.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/123.

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
