### PR TITLE
Added NotAuthorised and NotFoundPages

### PR DESCRIPTION
**Pull request by donalnofrixion**

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/131.

**Comment by pabloi-nf** [comment]
@donalnofrixion is there a way to test the forbidden access page?

**Review by sauravmaiti22 — APPROVED** [review]

**Review by Publicker — APPROVED** [review]

**Review by sipsorcery — APPROVED** [review]

**Review by arifmatin — APPROVED** [review]

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
image

The design wasn't considering to show the top navigation bar, that's why the nofrixion logo was placed on top.
I think it's OK to keep the navigation bar in this case if it helps the user to navigate to another section, but in that case  we should remove the logo.

Another thing to take into account is that the content box needs to be automatically centered in the vertical axis. In the screenshot can be seen the difference between the top and bottom margin.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/131.

**Comment by donalnofrixion** [comment]
@pabloi-nf I've made the requested changes.

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
