### PR TITLE
Payment requests loading issue fix

### PR DESCRIPTION
**Pull request by sauravmaiti22**
Refactored the way the loader, empty state component, skeleton and rows show up on the dashboard. As per new design the metrics, filter and create payment request button will always be visible. The only thing changing would be the table. Removed animate presence from dashboard as it was there because we had to remove filter, metrics and button from the dashboard, now they will be visible every time. Improved switching of merchant while on dashboard.  Need to test this on mobile when the pipeline is built. 

Used mutations for create and delete payment request.

I would request everyone to test it thoroughly and let me know if you see any issues.

I have done this for PR dashboard for now, will do it for payouts and transactions once this PR is approved to avoid rework.

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/75.

**Review by donalnofrixion — APPROVED** [review]

**Comment by donalnofrixion** [comment]
@sauravmaiti22 Just tried it on mobile. The "Show more" functionality is broken. Also the payment request cards are smaller then they should be.

**Review by donalnofrixion — CHANGES_REQUESTED** [review]
Just tried it on mobile. The "Show more" functionality is broken. Also the payment request cards are smaller then they should be.

**Comment by sauravmaiti22** [comment]
> @sauravmaiti22 Just tried it on mobile. The "Show more" functionality is broken. Also the payment request cards are smaller then they should be.

Thank Donal. I'll check.

**Comment by donalnofrixion** [comment]
https://github.com/nofrixion/nofrixion.business/assets/89344328/51128e7d-ba5c-4ce1-aa16-930430539964

**Comment by agranillonf** [comment]
There's a bug when filtering without getting any results and removing the filter afterwards. It seems the "Empty" state doesn't get correctly reset.
mm4b_empty_pr_error

**Review by agranillonf — CHANGES_REQUESTED** [review]
Other than the bug(s), code looks good.

**Comment by donalnofrixion** [comment]
The loader on mobile isn't centred. It's right of centre.

https://github.com/nofrixion/nofrixion.business/assets/89344328/fa9628ab-7dfa-471a-bbfa-e80aee1fadd3

**Comment by sauravmaiti22** [comment]
> There's a bug when filtering without getting any results and removing the filter afterwards. It seems the "Empty" state doesn't get correctly reset. mm4b_empty_pr_error [ mm4b_empty_pr_error ](https://user-images.githubusercontent.com/114026805/269970767-1a9ec91e-81e3-4608-9997-5e8a2ae0aede.gif) [ ](https://user-images.githubusercontent.com/114026805/269970767-1a9ec91e-81e3-4608-9997-5e8a2ae0aede.gif)

Thanks @agranillonf . Should be fine now.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/75.

**Review by donalnofrixion — APPROVED** [review]

**Comment by agranillonf** [comment]
Working fine now!

**Pull request merged**
