### PR TITLE
[MOOV-2078]: Fixed payment method icons being covered only on iOS

### PR DESCRIPTION
**Pull request by agranillonf**
Payment method icons on the Payment Request Details modal were being covered by the close button on iOS Chrome. This was due to Chrome's address/navigation bar eating up height when using 100vh. To circumvent this, [as per this discussion on StackOverflow](https://stackoverflow.com/questions/52848856/100vh-height-when-address-bar-is-shown-chrome-mobile), all `100vh` from the root html/body element up to the Payment Request Details component were changed to `h-full` (**100%**).

### CODE REVIEW

**Review by sipsorcery — APPROVED** [review]

**Review by donalnofrixion — APPROVED** [review]

**Review by pabloi-nf — APPROVED** [review]

**Review by Publicker — APPROVED** [review]

**Review by arifmatin — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/27.

**Comment by agranillonf** [comment]
@pabloi-nf You can now use the URL posted on the previous comment to test this particular PR instead of using the Storybook UI.

**Comment by donalnofrixion** [comment]
There's an issue with the dashboard page where the grey background doesn't  fill the screen.

NoFrixion

**Comment by donalnofrixion** [comment]
The login screen is also skewed 

NoFrixion (3)

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/27.

**Review by pabloi-nf — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/27.

**Review by donalnofrixion — APPROVED** [review]

**Pull request merged**
