### PR TITLE
Prevent Duplicate Tags in Payment Requests

### PR DESCRIPTION
**Pull request by Publicker**
Previously, users could add the same tag multiple times to a single Payment Request. This update prevents the addition of duplicate tags to a Payment Request.

# Changes
- **Duplicate Tag Prevention**: Implemented a check to disallow adding a tag to a Payment Request if it already exists.

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/150.

**Review by donalnofrixion — APPROVED** [review]

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
If the tag has a space added it allows its creation and it shows an error. This shouldn't happen.

https://github.com/nofrixion/nofrixion.business/assets/127946572/b768101d-4531-4fbd-8eca-fcfccf5499c0

The expected behaviour should be to keep the tag in gray in the list, but if the user writes the name we allow them to press the green button.

After they press the green button, we DON'T add the tag. Instead, we show a warning toast message in yellow saying "The tag 'XXX' is already applied".

image


Laura already updated the ticket with this.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/150.

**Comment by Publicker** [comment]
Thanks for your feedback @pabloi-nf! Both points were attended.

For everyone else, we had an internal chat with Pablo I. were we decided to change the toast text to: `'XYZ' tag was already added`

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
