### PR TITLE
Newly registered page

### PR DESCRIPTION
**Pull request by donalnofrixion**
Screenshot 2023-11-09 at 16 28 32

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/135.

**Review by sauravmaiti22 — APPROVED** [review]

**Review by arifmatin — APPROVED** [review]

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
I made a slight change. To reduce the padding-top of the gray text to be 0.5rem.

I found something weird when the page is reduced. The icon shrinks. It should stay the same.
image

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/135.

**Comment by donalnofrixion** [comment]
Hi @pabloi-nf I've fixed the padding and the icon resize issue.

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
