### PR TITLE
Fixed validation issue with IBAN

### PR DESCRIPTION
**Pull request by sauravmaiti22**
Fixed validation issue with IBAN and other fields.

The problem was that the validations for text fields were setting the validation message on change but the button click was not validating some of the fields.

Added all validation checks on button click instead of relying on messages.

Found another issue when merchant is switched and create payout button breaks. Fixed it.

### CODE REVIEW

**Review by donalnofrixion — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/62.

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
I can see that the amount field doesn't display the "REQUIRED" text, making it confusing if it's the only missing field and the error message is displayed.

https://github.com/nofrixion/nofrixion.business/assets/127946572/905422da-ee28-4a88-85cd-6dc8950facd2

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/62.

**Review by pabloi-nf — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/62.

**Pull request merged**
