### PR TITLE
[MOOV-2325] User details modal

### PR DESCRIPTION
**Pull request by donalnofrixion**

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/96.

**Review by sauravmaiti22 — APPROVED** [review]

**Review by Publicker — APPROVED** [review]
It looks great!!!

Just one thing I noticed: for invited users, there's no action when clicking on the row, which makes sense. I also observed that the cursor remains standard instead of turning into a pointer. Maybe we could consider removing the hover effect too?

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/96.

**Comment by donalnofrixion** [comment]
> It looks great!!!
> 
> Just one thing I noticed: for invited users, there's no action when clicking on the row, which makes sense. I also observed that the cursor remains standard instead of turning into a pointer. Maybe we could consider removing the hover effect too?

Good idea!

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/96.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/96.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/96.

**Review by pabloi-nf — COMMENTED** [review]
I would expect that if the link is expired and I resend the invitation, the link becomes available again. Right now it takes some time to change. My concern is if the user would think the "resend" didn't work as expected and keep clicking.
Is there a way to reduce the time or to change the text on the red pill?

image

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/96.

**Comment by donalnofrixion** [comment]
Hi @pabloi-nf I've addressed your comments.

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
