### PR TITLE
Changed tags visuals.

### PR DESCRIPTION
**Pull request by sauravmaiti22**
Changed tags visuals.

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/98.

**Review by donalnofrixion — APPROVED** [review]

**Review by arifmatin — APPROVED** [review]

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
The color of the text should be #454D54.

There is a strange animation where the icons move when trying to delete a tag, and the X icons staying static when the tags move after deleting a tag. 

https://github.com/nofrixion/nofrixion.business/assets/127946572/a4abc568-bd83-4c9b-8424-810cf0a553da

**Comment by sauravmaiti22** [comment]
> There is a strange animation where the icons move when trying to delete a tag, and the X icons staying static when the tags move after deleting a tag.

@pabloi-nf Fixed the color of the text. About the strange animation, I have created a bug https://nofrixion.atlassian.net/browse/MOOV-2366 as it is a pre-existing issue.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/98.

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
Thanks @sauravmaiti22. The text color has to be changed too on the tags on the table.

**Comment by sauravmaiti22** [comment]
> 454D54

Missed it. Thanks @pabloi-nf . Should be fixed now.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/98.

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
