### PR TITLE
Improve Responsiveness of Mobile Accounts Widget Card

### PR DESCRIPTION
**Pull request by Publicker**
This pull request enhances the responsiveness of the accounts widget card on mobile devices.

Changes made include adjustments to the layout and spacing to ensure that the accounts widget card displays optimally on mobile screens. These enhancements are based on the provided design.

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/134.

**Review by sauravmaiti22 — APPROVED** [review]

**Review by arifmatin — APPROVED** [review]

**Review by donalnofrixion — APPROVED** [review]

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
I think the 2 lines become too much. Can we change to truncation?
Also, let's align the text on top to the red line 
image

Thanks!

**Comment by Publicker** [comment]
@pabloi-nf Both comments attended!

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/134.

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
image
Almost there. I think we should have the same line-height for both texts (2rem) and no padding or margin top. Try what to do so they look optically centered

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/134.

**Comment by Publicker** [comment]
@pabloi-nf You're right, thanks! Should be better now.

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
