### PR TITLE
Add "All" Option to Date Range Picker

### PR DESCRIPTION
**Pull request by Publicker**
This pull request introduces an "All" option to the date range picker. When this option is selected, the date range filter will be disabled, retrieving all results.

Key Points:

- Results will continue to be paginated as usual.
- The displayed dates will range from the first day of the year when the merchant was created to the current day.
- The default option remains "Last 90 days", while the new "All" option is now listed last.
- This update affects both the Current Accounts and Payment Requests tables.

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/43.

**Comment by sipsorcery** [comment]
Does the date range need to show the year now? The "All" option start month could be from a previous year.

image

**Comment by Publicker** [comment]
@sipsorcery Yes! You're spot on and that is handled on the PR. The reason it doesn’t show the year is that January 1st falls within the current year, so it will only display when the year is different. You can test this by modifying the year associated with your merchant in the database or by adding "WebWizards Co" to your user, as that’s the merchant I altered for testing.

**Comment by sipsorcery** [comment]
@Publicker ok got it, thanks for clarifying.

While confirming this behavious I encountered another issue where the "All" filter doesn't adjust the dates te first time it's applied. It seems very weird but at least on a few tests the way I get it to correctly display the selected date range is by opening the browser's debug console.

https://github.com/nofrixion/nofrixion.business/assets/197660/fc2753a9-25aa-447c-8d4f-1d77b3f08e4f

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
The same happened to me. It doesn't take the date the first time you use it.
Also, the text should say "All", not "Custom".

image

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/43.

**Review by pabloi-nf — APPROVED** [review]

**Review by donalnofrixion — APPROVED** [review]

**Review by arifmatin — APPROVED** [review]

**Review by sipsorcery — APPROVED** [review]

**Pull request merged**
