### PR TITLE
Added font smoothing to entire app

### PR DESCRIPTION
**Pull request by donalnofrixion**
Updated turbo repo version

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/44.

**Review by arifmatin — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/44.

**Review by pabloi-nf — COMMENTED** [review]
@donalnofrixion I can see the property is applied to some texts, but not all. For example, the text in the PR creation screen don;'t have the property/

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/44.

**Review by pabloi-nf — APPROVED** [review]

**Review by Publicker — COMMENTED** [review]
After chatting with @pabloi-nf, he thinks this change should not just apply to MM4B but also to web-components. So, I believe we should add the 'antialiased' class to the parent elements of all web-components.

**Pull request merged**
