### PR TITLE
Truncate values if too long

### PR DESCRIPTION
**Pull request by donalnofrixion**

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/91.

**Comment by donalnofrixion** [comment]
image

**Review by Publicker — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/91.

**Comment by Publicker** [comment]
This issue is definitely solved. But in testing, I stumbled upon two other spots where really long names cause problems:

| Payment Request Details Modal (desktop) | Payment Request Details Modal (mobile) |
|--------|--------|
| Screenshot 2023-10-05 at 10 54 51 | Screenshot 2023-10-05 at 10 55 13 |
| QR code shows up tiny | QR button doesn't show up (it does, but you've to scroll horizontally to see it) |

**Comment by donalnofrixion** [comment]
> This issue is definitely solved. But in testing, I stumbled upon two other spots where really long names cause problems:
> 
> Payment Request Details Modal (desktop)	Payment Request Details Modal (mobile)
> Screenshot 2023-10-05 at 10 54 51	Screenshot 2023-10-05 at 10 55 13
> QR code shows up tiny	QR button doesn't show up (it does, but you've to scroll horizontally to see it)

@Publicker Can you create a bug to address?

**Pull request merged**
