### PR TITLE
Accounts Payable with Payruns Dashboard (only empty state) and Import Invoice Modal Integration

### PR DESCRIPTION
**Pull request by Publicker**
# Changes
1. **Payruns Dashboard**: Added a new dashboard with an empty state.
2. **Fixed DateRange State Issue**: Resolved a bug that caused the DateRange state to reset when navigating away from the Payout tab.
3. **Integrated Payouts into AccountsPayable**: Merged the Payouts functionality into the `AccountsPayable` component for better state management, removing the standalone `PayoutsDashboard`.
4. **UI Updates**: Updated the navbar icon and label for Accounts Payable, removing the “Soon” marker to reflect its current availability.
5. **Component Refactoring**: Replaced the MM4B Payouts page with the new AccountsPayable component to streamline the user interface.
6. **Import Invoice Modal Connection**: Added Payruns empty state with a connection to the Import Invoice modal. Importing an invoice from a CSV file now leads to a "Review page" for invoice selection and error review. The modal supports detailed error messages and allows users to choose which invoices to import.

# Notes
- Where an empty CSV is uploaded, users are directed to the "Review" tab without clear messaging. This user flow aspect may need further consideration.
- The "Download an invoice CSV template" button is currently non-functional and is planned for future implementation (waiting to have the template and upload it to the CDN).
- The Accounts Payable card on the MM4B home page directs to the new page but doesn't yet display real-time information, pending a separate task.
- It is recommended to delay merging this PR until the latest MM4B updates are deployed. I will be on holiday until January 15th, but if the PR receives all necessary approvals, please feel free to merge.

# Testing Files
- Working file with 18 invoices: [Invoices-working.csv](https://github.com/nofrixion/nofrixion.business/files/13687645/Invoices-working.csv)
- File with 4 errors: [Invoices-with-4-errors.csv](https://github.com/nofrixion/nofrixion.business/files/13687650/Invoices-with-4-errors.csv)
- File with 5 errors: [Invoices-with-5-errors.csv](https://github.com/nofrixion/nofrixion.business/files/13687655/Invoices-with-5-errors.csv)

# Demo videos:
### Backend Error Scenario
https://github.com/nofrixion/nofrixion.business/assets/52673485/69b2c756-f7d2-40ec-bbe4-8125273ce416

### Successful File Import
https://github.com/nofrixion/nofrixion.business/assets/52673485/0a9854ef-ac5a-467e-a053-a3d943d34e85

### Uploading a File with Errors and Tracking Fixes
https://github.com/nofrixion/nofrixion.business/assets/52673485/0c6208c4-b9d6-4a38-96f3-4f18e3af8a26

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/168.

**Comment by donalnofrixion** [comment]
Looks awesome!🔥

One minor issue. The highlighted tab is missing the rounded corners

image

**Review by donalnofrixion — APPROVED** [review]
🔥

**Comment by sipsorcery** [comment]
Amazing work, well done! 🔥🔥🔥

The videos are also great. We could use them as part of the promo/educaiton material.

**Review by sipsorcery — APPROVED** [review]

**Review by laucait — APPROVED** [review]

**Review by arifmatin — APPROVED** [review]

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
Looking good!

I can't see the implementation live, it shows me a white page.
Based on the videos I have 2 comments:

- The page title has to be "Accounts payable", not "Payruns".
- The error icons have to be all aligned. The ones on line 2 are more to the left than the other ones.
image

**Comment by Publicker** [comment]
Hey everyone! I'm back in action 🔥😎🤘🏻!

Thanks for all your feedback!

I've addressed the three comments that were mentioned, and the demo is up and running again for everyone to check out, especially you @pabloi-nf, since you were in holidays so you couldn't test it before it expired (links expire after some days, can't remember how many, but something like a week or so)!

I'll also be working on [MOOV-2626](https://nofrixion.atlassian.net/browse/MOOV-2626) in the meantime and will keep you posted once it's wrapped up. Thanks again!

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/168.

**Comment by Publicker** [comment]
Bugs [MOOV-2626](https://nofrixion.atlassian.net/browse/MOOV-2626) and [MOOV-2027](https://nofrixion.atlassian.net/browse/MOOV-2627) have been addressed!

Just a note on MOOV-2626: it mentions adjusting the distance between the reference column and the switch. I haven't made that change because currently, we're taking up all the space between them and aligning the switch to the far right. I wanted to get @pabloi-nf's feedback on this first, as it seems more intuitive to me rather than maintaining a consistent distance between the last column and the switch. What do you think, @pabloi-nf?

**Comment by pabloi-nf** [comment]
> Bugs [MOOV-2626](https://nofrixion.atlassian.net/browse/MOOV-2626) and [MOOV-2027](https://nofrixion.atlassian.net/browse/MOOV-2627) have been addressed!
> 
> Just a note on MOOV-2626: it mentions adjusting the distance between the reference column and the switch. I haven't made that change because currently, we're taking up all the space between them and aligning the switch to the far right. I wanted to get @pabloi-nf's feedback on this first, as it seems more intuitive to me rather than maintaining a consistent distance between the last column and the switch. What do you think, @pabloi-nf?

Yes, agree. This page adapts to the width of the screen. For a wider screen the switch would look more separated, because it's aligned to the right side of the table.

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
- The subtotal, discounts and taxes information is missing.
image

- The main switch becomes disabled if only one option is disabled. I think the opposite behaviour is more intuitive: to keep that switch enabled unless all of them are disabled.

https://github.com/nofrixion/nofrixion.business/assets/127946572/0f57c6fb-3f0d-4707-8f2a-0b6ea7bb6f4d

For dates, I've seen that it's common to avoid using the "th" ending. I'm starting to update this on our mockups, because it saves space and makes the date easier to read.
image
image
image

- The top padding on the rows is too big: it should have 1 rem on both sides.
image
image

- The gray text should be 0.875rem
image

- The distance between the title and the tabs, and between the tabs and the white box is too big.
image
image

image

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/168.

**Comment by Publicker** [comment]
Thanks once more for your feedback, @pabloi-nf! Everything's been taken care of, except for the modal related to subtotal, discounts, and taxes. Feel free to review the rest when you can.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/168.

**Comment by Publicker** [comment]
@pabloi-nf, the outstanding amount, subtotal, discounts, and taxes have all been included now! Looking forward to your feedback.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/168.

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
