### PR TITLE
Implement Payrun Status Handling and Display Across Screens

### PR DESCRIPTION
**Pull request by Publicker**
This PR introduces functionality to fetch Payrun status from the API and dynamically display it across various components in the application. It also incorporates logic to handle different Payrun states, ensuring the user interface reflects the current status accurately and controls user interactions based on the Payrun's lifecycle stage.

# Changes
- **Payrun Status Integration**: Implemented the retrieval of Payrun status from the API, displaying the status across different screens within the application.
- **Dynamic Status Badges**: Added status badges next to the Payrun names on the Payruns Dashboard. Note that the placement of these badges is temporary.
- **Conditional Editing in Payrun Details**: The Payrun Details screen now restricts editing functionalities based on the Payrun's status. Editing is only permitted if the Payrun status is "Draft". For Payruns with a status other than "Draft", a badge indicating the current status is displayed, and editing is disabled.
- **State Handling in Pre-Authorise Screen**: Enhanced the Pre-Authorise screen to conditionally load content based on the Payrun status. The screen is fully accessible for Payruns in the "Awaiting for Auth" state. For Payruns in "Draft" or "Already Authorised" states, appropriate messages inform the user of the current editing or authorisation status.

# Caveats
- **Pre-Authorise Screen Mechanism**: The current implementation in the Pre-Authorise screen provides basic logic for handling states other than "Awaiting for Auth". This mechanism will be refined to offer more nuanced feedback and options based on the Payrun's state.
- **Status Change Functionality**: Currently, there is no UI mechanism for changing a Payrun's status, such as moving it from "Draft" to "Awaiting for Auth". The capability to request authorisation and thereby test state-based behaviors fully will be addressed in upcoming updates.

# Screenshots
| Payrun Dashboard | Payrun Details - Draft | Payrun Details - Awaiting Auth | Authorise - draft state | Authorise - already authorised |
|--------|--------|--------|--------|--------|
| Payrun Dashboard | Details - Draft | Details - Awaiting Auth | Authorise - draft state | Authorise - already authorised |

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/201.

**Review by donalnofrixion — APPROVED** [review]

**Review by pabloi-nf — APPROVED** [review]

**Comment by Publicker** [comment]
@pabloi-nf @donalnofrixion I've updated the 'Pending' status to now display as 'Scheduled'. Additionally, once an authoriser selects 'Accept and continue' and then returns to that screen, the 'Reject' button will no longer be visible since the Payouts have already been created.

Here are screenshots showcasing both scenarios:

| Scheduled  | No reject button |
|--------|--------|
| Scheduled | No reject button |

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/201.

**Comment by Publicker** [comment]
Little caveat @pabloi-nf, if Payouts were created and 'Reject' button is not shown, when clicking on 'Accept and continue' nothing happens at the moment.

@donalnofrixion, we might need to consider returning the batch payout ID once payouts are created in the Payrun response. This way, from MM4B, we can direct users to the batch approval screen on the Identity Server. Without it, we're unable to do that redirection.

**Comment by donalnofrixion** [comment]
> Little caveat @pabloi-nf, if Payouts were created and 'Reject' button is not shown, when clicking on 'Accept and continue' nothing happens at the moment.
> 
> @donalnofrixion, we might need to consider returning the batch payout ID once payouts are created in the Payrun response. This way, from MM4B, we can direct users to the batch approval screen on the Identity Server. Without it, we're unable to do that redirection.

@Publicker That's done.
https://bitbucket.org/nofrixion/moneymoovapi/pull-requests/1575

**Comment by Publicker** [comment]
@donalnofrixion Awesome! Thanks Donal. I'll get to work on implementing this so the 'Accept and continue' button functions correctly in that scenario.

**Review by pabloi-nf — APPROVED** [review]

**Review by arifmatin — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/201.

**Comment by Publicker** [comment]
@donalnofrixion @pabloi-nf The 'Accept and continue' button now functions as intended, even when users arrive at the screen after Payouts have been created.

Thanks @donalnofrixion for quickly sorting out the backend part!

**Comment by donalnofrixion** [comment]
> I've also made some updates and adjustments to the code to incorporate the destination account name from the CSV, a field that hadn't been utilised until now. Along with this change, I've updated the CSV template. Here's the link to the new file I'll be using for demos, now including this new field: [invoices-working-4-beneficiaries.csv](https://github.com/nofrixion/nofrixion.business/files/14331438/invoices-working-4-beneficiaries.csv)

@Publicker The destination account name is now required on the api. I committed tis change this morning

**Comment by Publicker** [comment]
@donalnofrixion Yes, exactly. Changes have been implemented in MM4B (the details can be found [in this commit](https://github.com/nofrixion/nofrixion.business/pull/201/commits/aec49b798a60d642663f0e213a7b943e660013e9)), allowing for the destination account name to be added to the CSV. Additionally, it will now display an error message if the destination account name is omitted, ensuring it functions as intended.

**Pull request merged**
