### PR TITLE
Support for Scheduled Payouts

### PR DESCRIPTION
**Pull request by donalnofrixion**
1. When creating a Payout allow the user to choose the date when the payout is submitted.
2. Added "Scheduled" tab on payouts dashboard
3. Added "Scheduled" status badge

### CODE REVIEW

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/122.

**Review by arifmatin — APPROVED** [review]

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/122.

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
Looks good!
A few comments:

The icons are not vertically aligned in both sizes 
image
image

Now that we have another tab, I think we need to adjust the paddings to make the text fit better in smaller screen sizes.
We should use padding-left: 1.5rem and padding-right:1rem.
image

The radio button in the active state should have the border in the same green of the inside.
Right now it has a gray border that looks fuzzy.
image
image

If the option selected is "Immediatly", we should not have all that extra space under the radio component. The fields underneath have to be pushed down when the date field appears.
image

The font size inside the date component should be 14px (0.875rem)
image

When in editing mode, the "/" character should be masked, not allowing to delete it and not being count as editable.
image

The style for the selected day has poor contrast. We can change the green background color to have 40% opacity, and eliminate the shadow around it.
image

**Comment by donalnofrixion** [comment]
Hi @pabloi-nf I've made those changes requested plus the others we discussed including the scheduled column. With regards to the status badge, I adjusted the small one but I can't see a misalignment in the second one. Please check.

Screenshot 2023-10-25 at 14 54 36

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/122.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/122.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/122.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/122.

**Comment by sipsorcery** [comment]
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/122.

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
